### ISSUE TITLE
Install issue on Windows

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#291]
IOData didn't install on Windows. The workaround is to comment out line 56: "long_description=get_readme(),"

@PaulWAyers Can you paste the error message you get in a comment below? Thanks!

**Comment by PaulWAyers** [comment]
Running command git clone -q https://github.com/theochem/iodata.git 'C:\Users\ayers\AppData\Local\Temp\pip-req-build-inrbvm34'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ayers\anaconda3\envs\env_horton3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ayers\\AppData\\Local\\Temp\\pip-req-build-inrbvm34\\setup.py'"'"'; __file__='"'"'C:\\Users\\ayers\\AppData\\Local\\Temp\\pip-req-build-inrbvm34\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ayers\AppData\Local\Temp\pip-pip-egg-info-spjgcq28'
         cwd: C:\Users\ayers\AppData\Local\Temp\pip-req-build-inrbvm34\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ayers\AppData\Local\Temp\pip-req-build-inrbvm34\setup.py", line 56, in <module>
        long_description=get_readme(),
      File "C:\Users\ayers\AppData\Local\Temp\pip-req-build-inrbvm34\setup.py", line 47, in get_readme
        return fhandle.read()
      File "C:\Users\ayers\anaconda3\envs\env_horton3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1517: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding git+https://github.com/theochem/iodata.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by PaulWAyers** [comment]
A similar issue happens in [`AtomDB`](https://github.com/theochem/AtomDB)
